# Generated by Django 3.1.4 on 2020-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
